server.port=8081

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/user_service_db
spring.datasource.username=postgres
spring.datasource.password=super
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=dxbDX0IKF1bzyAVaDHv2lf8pe7VbKaGJZPJKVG5VkEHaBB1Dj4l3URBtjCzOPoEndz7tsMN5dlrCvTWGh/z2jA==
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000